# Generated by Django 5.1 on 2024-08-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarteiraAtivos',
            new_name='Carteira',
        ),
    ]
